schema_version = "1.0.0"

id = "render_exporter"
version = "0.0.1"
name = "Render Exporter"
tagline = "This is another extension"
maintainer = "Alec Chechik <alec.chechik@gmail.com>"
type = "add-on"

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
